-- AI_MENTION_ALARM job tipi ekle
ALTER TABLE `jobs` MODIFY COLUMN `type` ENUM(
  'SITE_AUDIT','AUTO_FIX','BRAIN_GENERATE','TOPIC_ENGINE','GENERATE_ARTICLE','PUBLISH_ARTICLE',
  'GENERATE_IMAGE','IMPROVE_PAGE','WEEKLY_BATCH','PERFORMANCE_CHECK','ONBOARDING_CHAIN',
  'SOCIAL_PUBLISH','PROCESS_SCHEDULED','LLMS_FULL_BUILD','AI_CITATION_DAILY','CONTENT_PIVOT_CHECK','AI_MENTION_ALARM'
) NOT NULL;
