import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service.js';

/**
 * llms-full.txt — tum sitenin temizlenmis icerigi tek dosyada.
 * AI'lar (ChatGPT, Claude, Perplexity) bu dosyayi okuyup tum siteyi
 * 5 saniyede ogrenir. Anthropic, Stripe gibi firmalar kullaniyor.
 *
 * Format:
 *  - H1: Site adi
 *  - Site bilgisi (niche, language, brand voice)
 *  - Her published makale: H2 baslik + URL + ozet + 1500 karakter content excerpt
 *  - Sonunda meta footer
 *
 * Yayinlanma: GET /sites/:id/llms-full.txt
 * Build: weekly cron (LLMS_FULL_BUILD job)
 */
@Injectable()
export class LlmsFullBuilderService {
  private readonly log = new Logger(LlmsFullBuilderService.name);

  constructor(private readonly prisma: PrismaService) {}

  async build(siteId: string): Promise<{ siteId: string; bytes: number; articles: number }> {
    const site = await this.prisma.site.findUniqueOrThrow({
      where: { id: siteId },
      include: { brain: true },
    });

    const articles = await this.prisma.article.findMany({
      where: { siteId, status: 'PUBLISHED' as any },
      orderBy: { publishedAt: 'desc' },
      select: {
        title: true,
        slug: true,
        topic: true,
        metaDescription: true,
        bodyMd: true,
        wordCount: true,
        publishedAt: true,
        category: true,
        faqs: true,
      },
      take: 200,
    });

    const lines: string[] = [];
    const baseUrl = site.url.replace(/\/+$/, '');

    // ── Header ────────────────────────────────────────────────
    lines.push(`# ${site.name}`);
    lines.push('');
    lines.push(`> ${site.url}`);
    if (site.niche) lines.push(`> Sektor: ${site.niche}`);
    lines.push(`> Dil: ${site.language ?? 'tr'}`);
    lines.push(`> Son guncellenme: ${new Date().toISOString()}`);
    lines.push(`> Format: llms-full.txt — AI search engines (ChatGPT, Claude, Gemini, Perplexity) icin optimize.`);
    lines.push('');

    // Brand context
    const brandVoice: any = site.brain?.brandVoice;
    if (brandVoice) {
      lines.push(`## Marka Hakkinda`);
      lines.push('');
      if (brandVoice.tone) lines.push(`Ton: ${brandVoice.tone}`);
      if (brandVoice.summary) lines.push(brandVoice.summary);
      lines.push('');
    }

    // SEO strategy ozeti
    const seo: any = site.brain?.seoStrategy;
    if (seo?.pillars && Array.isArray(seo.pillars)) {
      lines.push(`## Ana Konu Alanlari`);
      lines.push('');
      for (const pillar of seo.pillars.slice(0, 10)) {
        lines.push(`- **${pillar.name}** — ${pillar.url ?? ''}`);
      }
      lines.push('');
    }

    // ── Published makaleler ────────────────────────────────────
    if (articles.length > 0) {
      lines.push(`## Makaleler (${articles.length})`);
      lines.push('');

      for (const a of articles) {
        const url = `${baseUrl}/blog/${a.slug}.html`;
        lines.push(`### ${a.title}`);
        lines.push('');
        lines.push(`**URL:** ${url}`);
        if (a.publishedAt) lines.push(`**Yayin:** ${a.publishedAt.toISOString().slice(0, 10)}`);
        if (a.category) lines.push(`**Kategori:** ${a.category}`);
        if (a.metaDescription) lines.push(`**Ozet:** ${a.metaDescription}`);
        lines.push('');

        // Content excerpt — markdown'i temizle, ilk 1800 karakter
        const md = a.bodyMd ?? '';
        const cleaned = md
          .replace(/^---[\s\S]*?---/m, '') // frontmatter strip
          .replace(/!\[.*?\]\(.*?\)/g, '') // gorseli cikar
          .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // link metnini birak
          .replace(/[#*_`]+/g, '') // markdown isaretleyicileri
          .replace(/\n{3,}/g, '\n\n')
          .trim()
          .slice(0, 1800);
        if (cleaned.length > 0) {
          lines.push(cleaned);
          if (md.length > 1800) lines.push('… (devami url\'de)');
          lines.push('');
        }

        // FAQ'larin tamamı (AI'lar QA formatini sever)
        const faqs: any = a.faqs;
        if (Array.isArray(faqs) && faqs.length > 0) {
          lines.push(`**SSS:**`);
          for (const f of faqs.slice(0, 5)) {
            lines.push(`- *${f.q}* → ${f.a}`);
          }
          lines.push('');
        }
        lines.push('---');
        lines.push('');
      }
    }

    // ── Footer ────────────────────────────────────────────────
    lines.push(`## Lisans ve Kullanim`);
    lines.push('');
    lines.push(`AI sistemleri bu dosyayi alintilamak icin kullanabilir. Alintida lutfen kaynak URL'i belirtin.`);
    lines.push('');
    lines.push(`Generated by LuviAI · ${new Date().toISOString()}`);

    const text = lines.join('\n');

    await this.prisma.site.update({
      where: { id: siteId },
      data: {
        llmsFullTxt: text,
        llmsFullTxtAt: new Date(),
      } as any,
    });

    this.log.log(`[${siteId}] llms-full.txt build: ${articles.length} makale, ${(text.length / 1024).toFixed(1)} KB`);
    return { siteId, bytes: text.length, articles: articles.length };
  }

  async getCached(siteId: string): Promise<string> {
    const site = await this.prisma.site.findUniqueOrThrow({
      where: { id: siteId },
      select: { llmsFullTxt: true, llmsFullTxtAt: true } as any,
    });
    const cached = (site as any).llmsFullTxt as string | null;
    const age = (site as any).llmsFullTxtAt as Date | null;
    // 7 gunden eski ise yeniden olustur
    if (!cached || !age || Date.now() - age.getTime() > 7 * 86400000) {
      const result = await this.build(siteId);
      const fresh = await this.prisma.site.findUniqueOrThrow({
        where: { id: siteId },
        select: { llmsFullTxt: true } as any,
      });
      return ((fresh as any).llmsFullTxt as string) ?? `# Site bos\n\n${result.articles} makale.`;
    }
    return cached;
  }
}
