-- Article: scheduledAt sutunu + SCHEDULED enum degeri + index
ALTER TABLE `articles` ADD COLUMN `scheduledAt` DATETIME(3) NULL;
CREATE INDEX `articles_siteId_scheduledAt_idx` ON `articles`(`siteId`, `scheduledAt`);
ALTER TABLE `articles` MODIFY COLUMN `status` ENUM('DRAFT','SCHEDULED','GENERATING','EDITING','REVIZE_NEEDED','READY_TO_PUBLISH','PUBLISHED','FAILED','ARCHIVED') NOT NULL DEFAULT 'DRAFT';

-- Job tipi: PROCESS_SCHEDULED
ALTER TABLE `jobs` MODIFY COLUMN `type` ENUM('SITE_AUDIT','AUTO_FIX','BRAIN_GENERATE','TOPIC_ENGINE','GENERATE_ARTICLE','PUBLISH_ARTICLE','GENERATE_IMAGE','IMPROVE_PAGE','WEEKLY_BATCH','PERFORMANCE_CHECK','ONBOARDING_CHAIN','SOCIAL_PUBLISH','PROCESS_SCHEDULED') NOT NULL;
