-- ALTER `jobs.type` ENUM: ONBOARDING_CHAIN değeri eklendi
ALTER TABLE `jobs`
  MODIFY `type` ENUM(
    'SITE_AUDIT',
    'AUTO_FIX',
    'BRAIN_GENERATE',
    'TOPIC_ENGINE',
    'GENERATE_ARTICLE',
    'PUBLISH_ARTICLE',
    'GENERATE_IMAGE',
    'IMPROVE_PAGE',
    'WEEKLY_BATCH',
    'PERFORMANCE_CHECK',
    'ONBOARDING_CHAIN'
  ) NOT NULL;
